site_name: Asignaturas
nav:
  - Home: 'index.md'
  - Griego Moderno: 
    - Referencias: 'Griego_Moderno/GrMod_Bibl.md'
    - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_TODAS_Vocab.html'
    - Lección 1: 'Griego_Moderno/Leccion_01.md'
    - Lección 12:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_12_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_12.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_12_Exerc.html'
    - Lección 13:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_13_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_13.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_13_Exerc.html'
    - Lecciones 10-13:
      - Repaso: 'Griego_Moderno/Leccion_10_13.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_10_13_Exerc.html'
    - Lección 14:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_14_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_14.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_14_Exerc.html'
    - Lección 15:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_15_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_15.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_15_Exerc.html'
    - Lección 16:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_16_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_16.md'
      - Ejercicios: 'reveal.js-master/GMod_Leccion_16_Exerc.html'
    - Lección 17:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_17_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_17.md'
    - Lección 18:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_18_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_18.md'
    - Lección 19:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_19_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_19.md'
    - Lección 20:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_20_Vocab.html'
      - Lección 20: 'Griego_Moderno/Leccion_20.md'
    - Lección 21:
      - Vocabulario: 'Griego_Moderno/Vocabulario/Leccion_21_Vocab.html'
      - Lección 21: 'Griego_Moderno/Leccion_21.md'
    - Lección 22:
      - Vocabulario): 'Griego_Moderno/Vocabulario/Leccion_22_Vocab.html'
      - Lección: 'Griego_Moderno/Leccion_22.md'
    - Lecciones 14-22 (repaso): 'Griego_Moderno/Leccion_14_22.md'
  - Plutarco:
    - Guía (MESOB): 'Plutarch_Dion/Dion_MESOB.md'
    - Guía (Máster): 'Plutarch_Dion/Guia_Master.md'
    - Texto: 'Plutarch_Dion/Dion.md'
    - Traducción: 'Plutarch_Dion/Dion_Bilingue_02.md'
    - Estructura: 'Plutarch_Dion/Dion_Estructura.md'
    - Geografía: 
      - Sicilia: 'Plutarch_Dion/Geografia_Sicilia.md'
      - Geografía: 'Geografia/Talbert_New/Talbert.md'
      - Reveal: 'Plutarch_Dion/Sicilia_Mapa.html'
    - Bibliografía: 'Plutarch_Dion/Plutarco_Bib.md'
    - Edición: 
      - 'Zeitgler': 'Plutarch_Dion/Dion_Bruto_Teubner.pdf'
      - 'Chambry-Flaceliere': 'Plutarch_Dion/Dion_Belles_Lettres.pdf'
  - Homero: 
    - Instrumenta:
      - 'Comentarios':
        - 'Ilíada': 'Comentarios/Homer_Seymour.md'
        - 'Odisea': 'Comentarios/Homer_Merry_Monro.md'
      - 'Geografía': 'geografia.md'
      - 'Gramática breve': 
        - PDF: 'Morfologia/Homero_Lengua.pdf'
        - Web: 'Morfologia/Grammar_Homer.md'
      - 'Métrica': 'metric_Homer.md'
      - 'Nombres y epítetos': 'nombres_Homer.md'
      - 'Notas': 'notas.md'
      - 'Referencias': 'referencias.md'
      - 'Sintaxis': 'Homero_Sintax.md' 
      - 'Términos homéricos': 'terminos_Homer.md'
      - 'Verbos': 'verbo.md'
    - Textos:
      - 'Ilíada': 'textos_02.md'
      - 'Odisea': 'text_Odisea.md'
    - 'Traducciones': 
      - Ilíada: 'traduc_ES.md'
      - Odisea: 'Trad_Hom_Od.md'
  - Lengua:
    - 'Diccionarios':
      - 'Philolog.us': 'https://philolog.us'
      - 'Logeion': 'https://logeion.uchicago.edu'
    - 'Gramática': 'https://pajaro1966.github.io/Diccionario-Gramatical-GrAnt/'
    - 'Morfología flexiva': 'https://pajaro1966.github.io/Paradigmas_Griegos/'
    - 'Verbos': 'verbo.md'
    - Charlas:
      - 'Lengua de Homero': 'Charlas/Lengua_Homer/Homero_Lengua.html'
  - ANKI: 
    - 'Alumnos': 'Herramientas/Anki.md'
    - 'Presentación': 'Herramientas/Anki_02.md'
  - 'Innova 2024-2025': 
    - 'Proyecto_Innova_2024_2025/Solicitud.md'
    - 'gramatica.md'
  - 'Innova 2023-2024': 
    - 'Vocabulario/Vocab_Intro.md'
  - 'Naxos 2024': 'BIP_2024/Naxos_2024.md'
  - Pruebas:
    - Morfología: 'Morfologia/Morfologia_Todo.html'
    - Reveal: 'reveal.js-master/index_copia.html'
    - Pragmática: 'Pragmatica/Ejemplos.xml'
site_url: https://sitename.example
extra_css:
  - stylesheets/extra.css
  - stylesheets/mermaid.css
theme:
  features:
    - navigation.footer
    - toc.follow
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  icon:
    annotation: material/arrow-right-circle
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - md_in_html
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page
      toc_depth: 3
      permalink: true
extra_templates:
  - iframe.html
plugins:
  - privacy
  - search
extra_javascript:
  - javascripts/mermaid.min.js
  - javascripts/audio-control.js
  - javascript/lrc.js
  - javascript/karaoke.js
