site_name: Asignaturas
nav:
  - Home: index.md
site_url: https://sitename.example
extra_css:
  - stylesheets/extra.css
theme:
  features:
    - navigation.footer
    - toc.follow
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  icon:
    annotation: material/arrow-right-circle
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page
      toc_depth: 3
      permalink: true
extra:
  social:
    - icon: simple/youtube
      link: ""
    - icon: simple/linkedin
      link: ""
copyright: Copyright &copy; 2024 Antonio R. Revuelta Puigdollers