name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que esta sea tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force

